"""ローカル #include("...")を再帰展開して提出用の単一ファイルを生成する。

システムヘッダ(<...>)はそのまま残し、同一ファイルの二重展開は除去する。
展開後は -DONLINE_JUDGE 付きで構文チェックを行う。

    $ uv run ahc-tester/bundle.py                              # config の cpp_file → combined_file
    $ uv run ahc-tester/bundle.py --cpp solvers/beam.cpp --out submit.cpp
"""

import argparse
import os
import re
import subprocess
import sys

import config_util

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*(//.*)?$')
PRAGMA_ONCE_RE = re.compile(r"^\s*#\s*pragma\s+once\s*$")


def resolve_include(inc_path: str, including_file: str, work_dir: str):
    """g++ と同様に、include 元ファイルからの相対 → ルートからの相対の順で解決する。"""
    for base in (os.path.dirname(including_file), work_dir):
        cand = os.path.normpath(os.path.join(base, inc_path))
        if os.path.isfile(cand):
            return cand
    return None


def expand_file(path: str, work_dir: str, visited: set, out_lines: list, depth: int = 0):
    real = os.path.realpath(path)
    visited.add(real)
    rel = os.path.relpath(path, work_dir)
    if depth > 0:
        out_lines.append(f"// ==== begin {rel} ====")
    with open(path, "r", encoding="utf-8") as f:
        for raw in f.read().splitlines():
            m = INCLUDE_RE.match(raw)
            if m:
                target = resolve_include(m.group(1), path, work_dir)
                if target is None:
                    print(f'Warning: could not resolve #include "{m.group(1)}" in {rel} (kept as-is)')
                    out_lines.append(raw)
                elif os.path.realpath(target) in visited:
                    out_lines.append(f"// (duplicate include skipped: {os.path.relpath(target, work_dir)})")
                else:
                    expand_file(target, work_dir, visited, out_lines, depth + 1)
                continue
            if depth > 0 and PRAGMA_ONCE_RE.match(raw):
                continue
            out_lines.append(raw)
    if depth > 0:
        out_lines.append(f"// ==== end {rel} ====")


def syntax_check(out_path: str, work_dir: str) -> bool:
    cmd = ["g++", "-fsyntax-only", "-O2", "-DONLINE_JUDGE", out_path]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=work_dir)
    if result.returncode != 0:
        print("Syntax check failed (-DONLINE_JUDGE):")
        print(result.stderr)
        return False
    print("Syntax check passed (-DONLINE_JUDGE).")
    return True


def main():
    parser = argparse.ArgumentParser(description="Bundle local includes into a single submission file.")
    parser.add_argument("--cpp", default=None, help="Source file to bundle (default: config's cpp_file).")
    parser.add_argument("--out", default=None, help="Output path (default: config's combined_file).")
    parser.add_argument("--no-check", action="store_true", dest="no_check", help="Skip the g++ syntax check.")
    args = parser.parse_args()

    config = config_util.load_config()
    work_dir = config_util.work_dir()

    cpp_file = args.cpp or config["files"]["cpp_file"]
    cpp_path = cpp_file if os.path.isabs(cpp_file) else os.path.join(work_dir, cpp_file)
    if not os.path.isfile(cpp_path):
        print(f"Error: source file not found: {cpp_path}")
        sys.exit(1)

    out_file = args.out or config["files"].get("combined_file", "combined.cpp")
    out_path = out_file if os.path.isabs(out_file) else os.path.join(work_dir, out_file)

    out_lines = [f"// generated by bundle.py from {os.path.relpath(cpp_path, work_dir)}"]
    visited = set()
    expand_file(cpp_path, work_dir, visited, out_lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    n_files = len(visited)
    print(f"Bundled {n_files} file(s), {len(out_lines)} lines -> {os.path.relpath(out_path, work_dir)}")

    if not args.no_check:
        if not syntax_check(out_path, work_dir):
            sys.exit(1)


if __name__ == "__main__":
    main()
